---
title: "In-Class_Ex07b: Building an Isopleth Map with R"
author: "Roger Chen"
date: "09 Mar 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  freeze: true
  warning: false
  message: false
number-sections: true
editor: visual
---

# Overview

# Data Preparation

installing the packages

-   sf:

-   terra: to convert images into map data

-   gstat: geo statistical methods

```{r}
pacman:: p_load(sf, terra, gstat, tmap, viridis, tidyverse)
```

```{r}
rfstations <- read_csv("data/aspatial/RainfallStation.csv")
```

```{r}
rfdata <- read_csv("data/aspatial/DAILYDATA_202402.csv") %>%
  select(c(1,5)) %>%
  group_by(Station) %>%
  summarise(MONTHSUM = sum(`Daily Rainfall Total (mm)`)) %>%
  ungroup()
```

```{r}

# joining rfstation to rfdata, as there are many stations without data
## if we join rfdata to rfsattion, there will be a lot of stations without data
rfdata <- rfdata %>%
  left_join(rfstations)
```

```{r}
# first we tell sf the current data is in WGS84 system, then transform it to a geometric system (in meters)
rfdata_sf <- st_as_sf(rfdata,
                      coords = c("Longitude",
                                 "Latitude"),
                      crs= 4326) %>%
  st_transform(crs = 3414)
```

```{r}
#creating a boundary map
mpsz2019 <- st_read(dsn = "data/geospatial",
                    layer = "MPSZ-2019") %>%
  st_transform(crs = 3414)
```

```{r}
tmap_options(check.and.fix = TRUE)
tmap_mode("view")
tm_shape(mpsz2019) +
  tm_borders() +
  tm_shape(rfdata_sf) +
  tm_dots(col = "MONTHSUM")
tmap_mode("plot")
```

```{r}
#finding the width and height by calculating (xmax-xmin)/rast_grid and (ymax-ymin)/rast_grid
grid <- terra::rast(mpsz2019,
                    nrows = 690,
                    ncols = 1075)

#xy <- terra::xyFromCell(grid,
#                       1:ncell(grid))
```

```{r}

#coop <- st_as_sf